server:
  port: 8184
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/deptdb
    username: root
    
  jpa:
    show-sql: true