server:
   port: 8187
   
spring:
    application:
        name: management-gateway
              
eureka:
  client: 
      register-with-eureka: true
      service-url:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}   
          
management:
   endpoint:
       web:
         exposure:
            include:
            - '*'